//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neon.Aligner.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string UvCuringTime {
            get {
                return ((string)(this["UvCuringTime"]));
            }
            set {
                this["UvCuringTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public string UvOpenDistance {
            get {
                return ((string)(this["UvOpenDistance"]));
            }
            set {
                this["UvOpenDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UvCheckRight {
            get {
                return ((bool)(this["UvCheckRight"]));
            }
            set {
                this["UvCheckRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UvCheckLeft {
            get {
                return ((bool)(this["UvCheckLeft"]));
            }
            set {
                this["UvCheckLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44326")]
        public string UvStartingLeft {
            get {
                return ((string)(this["UvStartingLeft"]));
            }
            set {
                this["UvStartingLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44326")]
        public string UvStartingRight {
            get {
                return ((string)(this["UvStartingRight"]));
            }
            set {
                this["UvStartingRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point UvFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["UvFormLocation"]));
            }
            set {
                this["UvFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public string UvFinalDistance {
            get {
                return ((string)(this["UvFinalDistance"]));
            }
            set {
                this["UvFinalDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("94000")]
        public string UvCameraPosition {
            get {
                return ((string)(this["UvCameraPosition"]));
            }
            set {
                this["UvCameraPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("42000")]
        public string UvUvPosition {
            get {
                return ((string)(this["UvUvPosition"]));
            }
            set {
                this["UvUvPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9950")]
        public string UvCloseDistance {
            get {
                return ((string)(this["UvCloseDistance"]));
            }
            set {
                this["UvCloseDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Uv_DutType {
            get {
                return ((bool)(this["Uv_DutType"]));
            }
            set {
                this["Uv_DutType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UvCheckLeftAlign {
            get {
                return ((bool)(this["UvCheckLeftAlign"]));
            }
            set {
                this["UvCheckLeftAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UvCheckRightAlign {
            get {
                return ((bool)(this["UvCheckRightAlign"]));
            }
            set {
                this["UvCheckRightAlign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string UvApproachDistance {
            get {
                return ((string)(this["UvApproachDistance"]));
            }
            set {
                this["UvApproachDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UvAlignOpmPort {
            get {
                return ((int)(this["UvAlignOpmPort"]));
            }
            set {
                this["UvAlignOpmPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string UvCloseDistanceSlow {
            get {
                return ((string)(this["UvCloseDistanceSlow"]));
            }
            set {
                this["UvCloseDistanceSlow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string UvCloseSlowSpeed {
            get {
                return ((string)(this["UvCloseSlowSpeed"]));
            }
            set {
                this["UvCloseSlowSpeed"] = value;
            }
        }
    }
}
